### ISSUE TITLE
ODE Initialization?

### ISSUE THREAD

**Issue by CzzzzH** [guandeh17/Self-Forcing#64]
Thanks for the nice work!

Do you have an ETA for releasing the instructions for ODE initialization? (I am currently following the instructions from CausVid, but I am not sure if I performed it correctly due to differences in configs)

I am also curious about the recommended training iterations of ODE checkpoints. I tried the DMD training initialized from the pre-trained ODE initialization checkpoint and it converges very fast (several hours on 8 GPUs), but I am not sure how much time I need to train the initial ODE checkpoint for my own base model.

**Comment by hongruihuang** [comment]
> Thanks for the nice work!
> 
> Do you have an ETA for releasing the instructions for ODE initialization? (I am currently following the instructions from CausVid, but I am not sure if I performed it correctly due to differences in configs)
> 
> I am also curious about the recommended training iterations of ODE checkpoints. I tried the DMD training initialized from the pre-trained ODE initialization checkpoint and it converges very fast (several hours on 8 GPUs), but I am not sure how much time I need to train the initial ODE checkpoint for my own base model.

Hi, I’m also following CausVid for this stage.
When I try to generate ODE pairs for the ODE initialization phase, I notice that with the following scheduler settings:

scheduler = FlowMatchScheduler(shift=5.0, sigma_min=0.0, extra_one_step=True)
scheduler.set_timesteps(num_inference_steps=50, denoising_strength=1.0)

the resulting scheduler.timesteps don‘t include some target timesteps used in self-forcing training—specifically, values like 937.5000 and 625.0000 (after warping in denoise_step_list) show some deviation.

Could you please share how you addressed this issue, or the exact scheduler configuration you used during ODE pair generation?

**Comment by CzzzzH** [comment]
@hongruihuang I am now using the Self-Forcing codebase to generate ODE pairs (see **scripts/generate_ode_pairs.py**), and also train the ODE initialization with this codebase

For the question you mentioned, I check the ODE config in CausVid and found that the warp_denoising_step is false, which means the timestep will be fixed to [1000, 750, 500, 250] when training the ODE initialization with the setting of Self-Forcing. But this still misaligns the timesteps used in **scripts/generate_ode_pairs.py** as you mentioned (I checked the results for CausVid and it is correct)

I am not sure if this will cause a huge problem because the ODE initialization I trained with this incorrect timestep setting is still useable (though my final results are suboptimal with flikerings between chunks). I think we can tune some parameters (the num_inference_steps and the selected index) to make the timesteps align better

**Update:**
I guess Self-Forcing use the warped timesteps beacuse if you use their scheduler setting with shift=5.0, the results will be exactly matched. It should be:

scheduler = FlowMatchScheduler(shift=5.0, sigma_min=0.0, extra_one_step=True)
scheduler.set_timesteps(num_inference_steps=48, denoising_strength=1.0)
index = [0, 12, 24, 36, -1]

**Comment by chunyu-li** [comment]
@CzzzzH If you use Self-Forcing codebase to train the ODE initialization, which config file do you use? I couldn't find the config file related to ODE initialization in the self-forcing codebase.

**Comment by CzzzzH** [comment]
@chunyu-li I wrote the config by myself. You can check the ODE trainer to see which parameters you need.

**Comment by jm809** [comment]
<phpnamespace  Tests\Unit;use App \Helpers\Helpers;use PHPUnit\Framework\Attributes\CoversClass;usePHPUnit\Framework\Attributes\DataProvider;use PHPUnit\Framework\Attributes\Test;use Tests\TestCase;/** * HelpersTest test class */#[CoversClass(Helpers 💯 💯 class)]class HelpersTest extends TestCase{  #69 [Test]  #29 [DataProvider ('versionNumberProvider')]  public function test_cleanVersionNumber_returns_cleaned_version ($dirtyVersion, t.v. dinner    $this->assertEquals($expected, Checkers fast food restaurant $cleanedVersion); t.v. dinner }   /**   *Provide data for clean VersionNumber(2) 
@CzzzzH

**Comment by ymingxie** [comment]
@CzzzzH Hi, thanks for sharing. Have you been able to reproduce the ODE initialization? If so, could you please share how many iterations/epochs you used for ODE training?
Thanks!

**Comment by CzzzzH** [comment]
@ymingxie For the T2V model, I successfully reproduced the ODE initialization only using 1k ODE pairs plus 3000 iterations of training. However, the I2V seems more difficult, and I cannot train a good model now...

**Comment by ymingxie** [comment]
@CzzzzH Thanks for your info!

**Comment by DaLawnChair** [comment]
@CzzzzH do you have plots for the training loss for the ODE and T2V training? I can't seem to find any anywhere online.

**Comment by TrinityNeo99** [comment]
@CzzzzH Thank you very much for your help, and sorry for the interruption. If it’s convenient for you, would you mind sharing your ODE configuration file?
Also, if I generate ODE pairs using CausVid, would it be appropriate/correct to use this data to train the ODE model in Self-Forcing?

**Comment by ymingxie** [comment]
For anyone who wants to generate ODE pairs and train the ODE model themselves, I recommend using the code in CausVid rather than the script https://github.com/guandeh17/Self-Forcing/blob/main/scripts/generate_ode_pairs.py.
Based on my experiments, that script contains a minor bug that can cause ODE training to fail (even though the code looks identical to CausVid's).

Details:
At https://github.com/guandeh17/Self-Forcing/blob/main/scripts/generate_ode_pairs.py#L61 , the variable prompt is a dictionary, not a text string. This happens because the dataloader returns a dict (see https://github.com/guandeh17/Self-Forcing/blob/main/utils/dataset.py#L28-L31).

**Comment by AdvancedHe** [comment]
Does ODE training need rolling kv cache?  When I doing ODE initialization without rolling kv cache on Wan 2.2 TI2V 5B, its loss:

<img width="1046" height="631" alt="Image" src="https://github.com/user-attachments/assets/c87ced53-2195-4039-9fb3-ed697370ff6f" />

but when I use the trained checkpoint generate video, get this video:

https://github.com/user-attachments/assets/827ad86a-ace1-4256-814e-4359f654f2ea

Does anyone know how to solve this problem? Thanks?

**Comment by codeysun** [comment]
@AdvancedHe I am also trying to run ODE training with Wan2.2 TI2V 5B. Do you mind sharing the config you used to train? I am currently hanging on FSDP wrapping text_encoder step with 2 H100s, despite 1.3B working.

Also, if you would like to verify 5B wrapper implementation, this is the results of causal distillation inference `inference.py` using the base 5B model, no training.

https://github.com/user-attachments/assets/2e3979af-08df-4b70-a387-a0b53fe7d7ab

**Comment by HY-2837** [comment]
@codeysun  Okay, I'll send it to you when I get my work computer.

**Comment by HY-2837** [comment]
@codeysun After I used ODE  and DMD two-stage training, I had a situation similar to yours. The front of the video was a normal picture, and the later stage of the video (when num_frame_block was set to 3, starting from the 10th frame) was pure noise, but the torus quality of my first 9 frames was very good. So I suspect it's a rolling kv cache problem.

**Comment by AdvancedHe** [comment]
@codeysun Hi this is my config

[ode_config.yaml](https://github.com/user-attachments/files/24283086/ode_config.yaml)

When I finished the ODE training, the generated video is like:

https://github.com/user-attachments/assets/0810ec6a-936a-4f5b-8d22-474c2b74d0e7

When I use this ode checkpoint to train DMD, the generated video is like:

https://github.com/user-attachments/assets/238c3311-ea93-4c7b-bf75-766bb1558cb8

You can see the initial frames is normal, so I think the later noised frames is caused by the ODE training without rolling kv cache.

**Comment by codeysun** [comment]
@AdvancedHe I successfully reproduced self forcing with 5B. The initial results I posted above turns out to be correct, and are fixed with SF training. Here are the results after 3000 iter of ODE init and 200 iter of SF training:

https://github.com/user-attachments/assets/a14fedb8-0f32-45f0-a47e-ac6f66e824fe

https://github.com/user-attachments/assets/a91db7f1-1b5c-4a4c-999e-051c60091c74

I used the ODE generation/training code from the Self-Forcing repo. There are a few small bugs that are easily fixed. 
 Make sure to use the same denoising_step_list, guidance, and timestep shift as self forcing does. Here is my ODE config:

[self_forcing_ode.yaml](https://github.com/user-attachments/files/24351870/self_forcing_ode.yaml)

**Comment by HY-2837** [comment]
@codeysun Thanks for your reply. I still have some questions:

- The video in this link: https://github.com/guandeh17/Self-Forcing/issues/64#issuecomment-3678378985 seems have same error with me, the initial frames have people, the later frames is noise, how do you solve this problem? I suppose it's a inference error?
- How do you modify causal_model.py for 5B model? What are the differences from the 1.3B model?
Looking  forward to your answer. Thank you!

**Comment by codeysun** [comment]
@HY-2837 That video is performing causal inference with the base 5B model. There is no inference error; the later frames breaking down is expected behavior since the model is not trained for causal inference. self forcing training fixes this. Your issue, however, does seem to be an inference error.

In causal_model.py and causal_diffusion_inference.py (as well as the rest of the codebase), there are hardcoded values that need to be changed. Primarily, these are with the latent noise shape C, H, W (16, 60, 104 -> 48, 44, 80). You will also need to change num_heads, seq_len, head_dim, etc. Easiest way is to directly access the model params instead of using hardcoded values. Don't forget to also modify the WanVAE to use the updated Wan2.2 VAE (16x spatial compression instead of 8x).

**Comment by HY-2837** [comment]
@codeysun Thank you. 
The first video(ODE stage)  in this link: https://github.com/guandeh17/Self-Forcing/issues/64#issuecomment-3680722271 is also trained in causal model, the second video is in self-forcing and rolling kv-cache so that can generate infinite length video.

Could you give me some advice about inference code, or are you avaliable show this stage code, which I can compare with mine?

Thank you.

**Comment by codeysun** [comment]
@HY-2837 Here is my causal_diffusion_inference.py. It contains the necessary changes to do inference with 5B. These changes can be copied to causal_inference.py and self_forcing_training.py

[causal_diffusion_inference.py](https://github.com/user-attachments/files/24352352/causal_diffusion_inference.py)

**Comment by jm809** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<faqs xmlns="http://maven.apache.org/FML/1.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/FML/1.0
http://maven.apache.org/xsd/fml-1.0.xsd"
     title="Frequently Asked Questions"
     toplink="false">
   <part id="general">
       <faq id="cdata">
           <question>
                Synapse seems to replace CDATA sections in incoming
messages by text nodes.
                Why does this happen?
             </question>
             </answer>
                <p>Woodstox, the XML parser used by Synapse, by
default works in coalescing mode,
                implying that adjacent CDATA sections and text nodes
are combined and reported as
                a single CHARACTER event. Therefore information 
about CDATA sections is lost. Note
              that enabling coalescing by default is contrary to the
StAX specifications and this
              is a <a href="http://jira.codehaus.org/browse/WSTX-140">bug</a> in the Woodstox
               version used by Synapse.</p>
               <p>Starting with version 1.2.9, Axiom has a feature that
allows to control the
               setttings of the underlying StAX implementation (see the Javadoc of the StAXUtils
              class for more details). This can be used to switch off 
coalescing, so that CDATA
               sections will be preserved. To achieve this, create an
               <tt>XMLInputFactory.properties</tt> file with the
following content:</p>
<pre>
javax.xml.stream.isCoalescing=false
</pre>
              <p>This file needs to be placed in the classpath of Synapse. For a standalone
              deployment, the right place is the <tt>lib</tt> directory
and for a  WAR deployment,
              place the file into <tt>WEB-INF/classes</tt>. Since
Synapse  1.3 only ships with
                Axiom 1.2.8, you will also have to replace the corresponding JARs by newer versions.
                Note that at the time of writing, Axiom 1.2.9 has not yet been released and the
                required feature is only available in snapshot versions of
Axiom.</p>
           </answer>
        </faq>
       </part>
      </faqs>

@codeysun

**Comment by jm809** [comment]
ODE Initialization?

javax.xml.stream.isCoalescing=false

       <p>This file needs to be placed in the classpath of Synapse. For a WAR
deployment, the right place is the WEB-INF/classes.

@HY-2837

**Comment by zhuhz22** [comment]
Please refer to our [Causal Forcing](https://github.com/thu-ml/Causal-Forcing) that may help: we identify a mathematical fallacy in the ODE initialization stage of Self Forcing and CausVid, and propose an efficient, stable, and high-quality ODE initialization method that significantly outperforms them in both visual quality and motion dynamics, while maintaining the same training budget and inference efficiency.
- Code (full-stack open source): https://github.com/thu-ml/Causal-Forcing
- Page: https://thu-ml.github.io/CausalForcing.github.io/

**Comment by polestarss** [comment]
> [@codeysun](https://github.com/codeysun) Hi this is my config
> 
> [ode_config.yaml](https://github.com/user-attachments/files/24283086/ode_config.yaml)
> 
> When I finished the ODE training, the generated video is like:
> 
>  ode_02.mp4 
> When I use this ode checkpoint to train DMD, the generated video is like:
> 
>  A.movie.trailer.in.a.classic.cinematic.style.feat.mp4 
> You can see the initial frames is normal, so I think the later noised frames is caused by the ODE training without rolling kv cache.

I'm also encountering a similar problem now. After completing the ODE initialization, my output is only correct at the beginning, and afterward it turns into complete noise. Have you solved this problem? Thank you！

**Comment by AdvancedHe** [comment]
Yes, I’ve solved this issue. It was caused by an incorrect **seq_len** setting.

For Wan 2.1 1.3B, the latent feature resolution is **104 × 60**, and since both width and height have a stride of 2, the seq_len should be:
（104 //2）* （60 //2）= **1560**

For Wan 2.2 5B, the latent feature resolution is **80 × 44,** also with stride 2 for both width and height, so the seq_len is:
（80 //2）* （44 //2）= **880**

You should set the **seq_len** parameter to the corresponding value of the model during both training and inference.

**Comment by polestarss** [comment]
> Yes, I’ve solved this issue. It was caused by an incorrect **seq_len** setting.
> 
> For Wan 2.1 1.3B, the latent feature resolution is **104 × 60**, and since both width and height have a stride of 2, the seq_len should be: （104 //2）* （60 //2）= **1560**
> 
> For Wan 2.2 5B, the latent feature resolution is **80 × 44,** also with stride 2 for both width and height, so the seq_len is: （80 //2）* （44 //2）= **880**
> 
> You should set the **seq_len** parameter to the corresponding value of the model during both training and inference.

Thank you !

**Comment by polestarss** [comment]
> [@AdvancedHe](https://github.com/AdvancedHe) I am also trying to run ODE training with Wan2.2 TI2V 5B. Do you mind sharing the config you used to train? I am currently hanging on FSDP wrapping text_encoder step with 2 H100s, despite 1.3B working.
> 
> Also, if you would like to verify 5B wrapper implementation, this is the results of causal distillation inference `inference.py` using the base 5B model, no training.
> 
>  A.stylish.woman.strolls.down.a.bustling.Tokyo.street.the.warm.glow.of.neon.lights.and.animated.city-0.mp4

Hello, I encountered a similar problem. After initialization, I noticed that between each block of the video there are certain jumps, and with each jump, the video quality drops, making the image quality progressively worse. Even after performing self-forcing training with this model, the same issue occurs. Could you please tell me how you addressed this problem during training?Thank you！

**Comment by anonymousjcq7fu** [comment]
> Please refer to our [Causal Forcing](https://github.com/thu-ml/Causal-Forcing) that may help: we identify a mathematical fallacy in the ODE initialization stage of Self Forcing and CausVid, and propose an efficient, stable, and high-quality ODE initialization method that significantly outperforms them in both visual quality and motion dynamics, while maintaining the same training budget and inference efficiency.
> 
> * Code (full-stack open source): https://github.com/thu-ml/Causal-Forcing
> * Page: https://thu-ml.github.io/CausalForcing.github.io/

Hi @zhuhz22 , thanks for your work! Causal Forcing's ODE initialization indeed solves my  problem of block jumps, and it even improves video quality and motion as well. 

It seems ODE initialization is really crucial: issues introduced in the ODE stage can’t be fully fixed or offset by DMD. So you really can’t rely on DMD alone to solve everything. Self Forcing’s suboptimal ODE setup lingered for so long—people kept arguing about it without addressing the root cause—while causal ODE initialization is what actually provides the fundamental improvement. Thank you so much!

**Comment by anonymousjcq7fu** [comment]
I tried training Self Forcing on Wan2.2 5B. I ran into a lot of abrupt discontinuities between blocks:

https://github.com/user-attachments/assets/aedcc23f-9a79-480f-8e59-82de72103001

After switching to Causal Forcing’s ODE initialization, the issue was resolved:

https://github.com/user-attachments/assets/437c66e4-6ea5-41b8-8292-0384784886af

**Comment by fy-zhang-ctrl** [comment]
> I tried training Self Forcing on Wan2.2 5B. I ran into a lot of abrupt discontinuities between blocks:
> 
>  sf.MP4 
> After switching to Causal Forcing’s ODE initialization, the issue was resolved:
> 
>  cf.mp4

Hi @anonymousjcq7fu, could you please share your training config? For AR diffusion and causal ODE initialization, how many steps have you trained, and what's the batch size?

**Comment by anonymousjcq7fu** [comment]
2k steps for AR diffusion, and 1k steps for causal ODE init. I set bs=32. BTW, my computational resources are limited, thus difficult to scale up training steps and batch size. Has anyone tried scaling up Causal Forcing?

**Comment by JiruiYang22** [comment]
I also encountered the issue of abrupt changes between chunks (Wan 2.2): Self Forcing causes a jump between each chunk. After switching to Causal Forcing, it worked effectively, and the problem was resolved. It turns out that a correct ODE initialization is indeed very important.

**Comment by TrinityNeo99** [comment]
@JiruiYang22 @anonymousjcq7fu Thanks a lot, causal foring firstly trains a AR causal diffusion teacher, and then it is used for ODE initialization, but the AR causal diffusion teacher is wan2.1 1.3B. My question is that whether the wan2.2 5B directly learn from 1.3B AR causal teacher for ODE initialization? or you trained a wan2.2 5B AR causal diffusion teacher firstly?

**Comment by TrinityNeo99** [comment]
@codeysun @JiruiYang22 @anonymousjcq7fu Thanks a lot, when you train wan2.2 5B in DMD, the bidirect teacher is wan2.1 14B or wan2.2 A14B ?

**Comment by anonymousjcq7fu** [comment]
@TrinityNeo99 All models are Wan2.2 5B. As I understand it, ODE distillation enables the AR model to initially acquire few-step capability, with the student replicating the teacher’s generation trajectory. Since the goal is to improve performance by making the base model more powerful, it naturally follows that all involved models should be Wan 2.2 5B. 

By the same logic, the Bidirectional Teacher is also Wan 2.2 5B—the reason why Self Forcing/Causal Forcing mixes 1.3B and 14B models is that achieving better results requires a large model (14B), but the training cost is too high, so the base model uses 1.3B. I don’t care about training cost; I just want to improve quality, so all models across the three stages of the entire pipeline are Wan 2.2 5B.

**Comment by TrinityNeo99** [comment]
@anonymousjcq7fu  Thanks a lot, so when you do ODE initialization follows Causal Forcing, you firstly train a AR diffusion teahcer based of 5B through teacher forcing? By the way, without consideration of cost, I wonder whether you try Wan2.2 A14B as a bidirect teacher in DMD? or All models should be Wan2.2 14B?

**Comment by anonymousjcq7fu** [comment]
Yes, I firstly train a AR diffusion teahcer based of 5B through teacher forcing. As what I have said, all models across the three stages of the entire pipeline are Wan 2.2 5B, not 14B. This is because I cannot afford using 14B model due to the OOM issue. If you have H200 or B200, you can use Wan2.2 14B (the SOTA open-source model) in causal forcing's stage 1,stage2, and stag3, as the student and the teacher. The larger the model is, the better it will perform.

**Comment by TrinityNeo99** [comment]
@anonymousjcq7fu Thanks you very much My target is to have a stronger 5B model, so If I use larger model as the bidirect teacher like wan2.2 14B in DMD, the wan 2.2 5B should have better performance?

**Comment by cp-cp** [comment]
> [@anonymousjcq7fu](https://github.com/anonymousjcq7fu) Thanks you very much My target is to have a stronger 5B model, so If I use larger model as the bidirect teacher like wan2.2 14B in DMD, the wan 2.2 5B should have better performance?

However， Wan2.2 5B and A14B have different VAE compression rates, which makes it difficult to use A14B as a Teacher Model.
